- uses: Platane/pacman-contrib-graph@main
  with:
    github_user_name: dinesh-fullstackwebdeveloper
    outputs: |
      ./output/pacman-contribution-graph.svg
      ./output/pacman-contribution-graph-dark.svg
